### ISSUE TITLE
Повторное создание поселения

### ISSUE THREAD

**Issue by Otr1n** [Envel-Nikita-Gutsenkov/Goodmc.-Original.-Source-code.-#10]
После удаления поселения невозможно создать новое командой /l create, требует 4000$ на депозите. То же самое при попытке автоматического создания поселения при команде /l claim.
https://imgur.com/a/iwkLScM

**Comment by Envel-Nikita-Gutsenkov** [comment]
исправим в след версии

**Comment by Envel-Nikita-Gutsenkov** [comment]
Исправлено в патче 10.
