### ISSUE TITLE
4

### ISSUE THREAD

**Issue by Otr1n** [Envel-Nikita-Gutsenkov/Goodmc.-Original.-Source-code.-#4]
Задержку при релоге лучше сделать не при первом перезаходе, а при повторном. Иногда необходимо перезайти, чтобы отобразились невидимые блоки, либо если завис на месте (например при телепорте на неполный блок, или неудачно слез с лодки).

**Comment by Envel-Nikita-Gutsenkov** [comment]
Будет уменьшена
