### ISSUE TITLE
5 Откат /spawn

### ISSUE THREAD

**Issue by Otr1n** [Envel-Nikita-Gutsenkov/Goodmc.-Original.-Source-code.-#5]
Откат начинается, даже если телепорта не произошло (в течение 6 сек двигался после команды).
Отсутствуют нормальные дороги к спавну, в том числе хаб. Пока их нет, откат лучше убрать, т.к. в тот же шахтерский мир можно попасть только со спавна.

**Comment by Envel-Nikita-Gutsenkov** [comment]
Исправим телепортации, но задержка должна быть

**Comment by Otr1n** [comment]
![2019-09-29_16 44 06](https://user-images.githubusercontent.com/53965932/65832203-e7c23580-e2ea-11e9-915a-366139b65a10.png)
Откат начался после неудачной телепортации
