### ISSUE TITLE
7 Респ в аду

### ISSUE THREAD

**Issue by Otr1n** [Envel-Nikita-Gutsenkov/Goodmc.-Original.-Source-code.-#7]
После смерти закинуло на бедрок 2 раза подряд (1-й раз спас /spawn).
За день до этого после смерти респало в одни и те же координаты в аду над лавой до релогина. После телепортировало на спавн.

**Comment by Envel-Nikita-Gutsenkov** [comment]
Данный баг был исправлен в патче за сегодня, мы проверим это заново.

**Comment by Envel-Nikita-Gutsenkov** [comment]
Исправим в след версии, проявляется, если не поспать

**Comment by Envel-Nikita-Gutsenkov** [comment]
исправлено в патче 11
